### ISSUE TITLE
slider images are different for mobile view and laptop view.

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#137] opened 2018-04-25 15:41 UTC

**Comment by Rajrox97** [comment] 2018-04-26 12:33
@souro18  Can you please elaborate a bit more on this issue?

**Comment by souro18** [comment] 2018-04-26 12:45
Notice the slider images in laptop/desktop view(newly added by priyabrata ) and then switch to mobile view. You will notice that in mobile view the images are different(old one)

**Comment by i-shubhamprakash** [comment] 2018-04-30 10:43
Hi @souro18 , Can you please provide some screenshots to clarify exactly what the issue is.

**Comment by Rajrox97** [comment] 2018-05-01 12:32
@souro18 go ahead and make the mobile version like the desktop one.

**Comment by Rajrox97** [comment] 2018-05-01 12:41
This issue is already resolved in an upcoming PR.

**Closed by Rajrox97** 2018-05-01 12:41 UTC
